### ISSUE TITLE
Could you add a License file please

### ISSUE THREAD

**Issue by BrunoVernay** [stump/libsmf#6]
A LICENSE file is welcomed for packaging (RPM, DEB, ...) 
it eases the acceptance in Official Repos.
If I am not mistaken, Github allows you to add this file just by choosing in a dropdown list :-)
Thanks

**Comment by stump** [comment]
There already is one under its more traditional name of COPYING.

**Comment by BrunoVernay** [comment]
Oups, indeed. So a  [2-clause license ("Simplified BSD License" or "FreeBSD License")](https://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_(%22Simplified_BSD_License%22_or_%22FreeBSD_License%22))
